#!/bin/bash

percent=$(pmset -g batt | grep -Eo "\d+%" | cut -d% -f1)

if   (( percent > 80 )); then color='#[nobright fg=green]'
elif (( percent > 65 )); then color='#[bright fg=yellow]'
elif (( percent > 40 )); then color='#[bright fg=red]'
                         else color='#[nobright fg=red]'
fi

echo "$color$percent%"
